### PR TITLE
ADD more presets

### PR DESCRIPTION
**Pull request by allanlaal**

### CODE REVIEW

**Comment by inikishev** [comment]
those dont work ඞ

**Comment by inikishev** [comment]
and are sus

**Comment by allanlaal** [comment]
4o created them, I guess it was wrong. I retract my patch :)

**Comment by inikishev** [comment]
> 4o

yeah, well it did better than when I tried it using google bard, would be cool if it could actually create new presets, but ig its a pretty hard task, it has to understand how to rearrange beats

**Comment by allanlaal** [comment]
this is an old method anyway

I wish there was a proper AI that could do remixes of vocals to a certain song

**Pull request closed without merging**
